#!/usr/bin/env node
// send.mjs — Thin outbound email sender for Tula visit prep packages.
// Uses a SEPARATE Entra app registration (Mail.Send scope only).
// Never reuse the inbound router's token cache or client ID.
//
// Usage (from within prep-my-visit or manually):
//   node send.mjs --visit-id zepbound-90day-followup \
//     --to paul@example.com \
//     --subject "Your Visit Prep Package" \
//     --body "Hi Paul, your provider.pdf and patient.pdf are attached." \
//     --attachments "provider.pdf,patient.pdf"
//
// Expects TULA_SEND_CLIENT_ID and TULA_SEND_TENANT_ID in env (separate app).

import fs from 'node:fs/promises';
import path from 'node:path';
import { Client } from '@microsoft/microsoft-graph-client';
import { buildPcaForSend, getSendToken } from './auth-send.mjs';

function parseArgs(argv) {
  const opts = { attachments: [] };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--visit-id') opts.visitId = argv[++i];
    else if (a === '--to') opts.to = argv[++i];
    else if (a === '--subject') opts.subject = argv[++i];
    else if (a === '--body') opts.body = argv[++i];
    else if (a === '--attachments') {
      opts.attachments = argv[++i].split(',').map(s => s.trim());
    }
  }
  if (!opts.visitId || !opts.to || !opts.subject || !opts.body) {
    console.error('Missing required args: --visit-id, --to, --subject, --body');
    process.exit(2);
  }
  return opts;
}

async function main() {
  const opts = parseArgs(process.argv.slice(2));

  const pca = await buildPcaForSend();
  const tokenResult = await getSendToken(pca);

  const client = Client.init({
    authProvider: (done) => {
      done(null, tokenResult.accessToken);
    },
    defaultVersion: 'v1.0',
  });

  // Build attachments
  const attachments = [];
  for (const filename of opts.attachments) {
    const filePath = path.join(process.cwd(), filename); // caller must be in the right dir or pass full paths
    try {
      const contentBytes = await fs.readFile(filePath);
      attachments.push({
        '@odata.type': '#microsoft.graph.fileAttachment',
        name: filename,
        contentBytes: contentBytes.toString('base64'),
      });
    } catch (err) {
      console.error(`Failed to read attachment ${filename}:`, err.message);
      process.exit(5);
    }
  }

  const message = {
    subject: opts.subject,
    body: {
      contentType: 'HTML',
      content: opts.body + '<br><br><small>This is your personal health summary generated by Tula. It is not a substitute for medical advice. Please discuss all questions with your clinician.</small>',
    },
    toRecipients: [{ emailAddress: { address: opts.to } }],
    attachments,
  };

  console.log(`Sending email to ${opts.to} with ${attachments.length} attachment(s)...`);
  const sendResult = await client.api('/me/sendMail').post({ message });

  console.log('Email sent successfully.');
  return { graphMessageId: sendResult?.id || 'unknown' };
}

main().catch(err => {
  console.error('Send failed:', err?.message ?? err);
  process.exit(1);
});